# .github/workflows/example.yml
name: Build and Push OpenVPN
on:
  push:

permissions:
      id-token: write
      contents: write    # This is required for actions/checkout@v1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::773378664514:role/github-openvpn
          role-session-name: samplerolesession
          aws-region: eu-west-1
      - name: Docker Login
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/y9x3p3i6
      - name: Docker Builld
        run: docker build -t openvpn .
      - name: Docker Tag
        run: docker tag openvpn:latest public.ecr.aws/y9x3p3i6/openvpn:${{ github.run_number }}
      - name: Docker Push
        run: docker push public.ecr.aws/y9x3p3i6/openvpn:${{ github.run_number }}

